name: CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  linux:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: apt install
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update -qq
        sudo apt-get install -y gcc-5 g++-5
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
        sudo apt-get install -y libx11-dev libxtst-dev libxt-dev libx11-xcb-dev
        sudo apt-get install -y libxkbcommon-dev
        sudo apt-get install -y libxkbcommon-x11-dev
        sudo apt-get install -y xorg-dev
        sudo apt-get install -y libxcb-xkb-dev
        sudo apt-get install -y libxkbfile-dev
        sudo apt-get install -y libxinerama-dev
    - run: npm i --ignore-scripts
    - run: npm run build -- --all
    - name: artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-prebuilds
        path: prebuilds
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: npm i --ignore-scripts
    - run: npm run build -- --all
    - name: artifacts
      uses: actions/upload-artifact@v2
      with:
        name: macos-prebuilds
        path: prebuilds
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: install Visual Studio 2017 (MSBuild 14.0)
      run: npm install --global windows-build-tools@4
    - run: dir "C:\Program Files (x86)\MSBuild"
    - run: npm i --ignore-scripts
    - run: |
        set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
        for /f %%i in ('node -v') do set exact_nodejs_version=%%i
        npm run build -- --all
      shell: cmd
    - name: artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows-latest
        path: prebuilds
    







