on: [release, workflow_dispatch]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libx11-dev libxtst-dev libxt-dev libx11-xcb-dev libxkbcommon-dev libxkbcommon-x11-dev xorg-dev libxcb-xkb-dev libxkbfile-dev libxinerama-dev
          npm install --ignore-scripts
      - name: Build
        run: npm run build:ci
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm install --ignore-scripts
      - name: Build
        run: npm run build:ci
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows:
    runs-on: windows-2016
    strategy:
      matrix:
        arch: [x86_64, i686]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: set ARCH=${{ matrix.arch }}
      - name: Install dependencies
        run: npm install --ignore-scripts
      - name: Set Windows environment
        run: |
          echo 'GYP_MSVS_VERSION=2015' >> $Env:GITHUB_ENV
          echo 'GYP_MSVS_OVERRIDE_PATH=C:\\Dummy' >> $Env:GITHUB_ENV
      - name: Build
        run: npm run build:ci
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
